-- return {
--   {
--     "mfussenegger/nvim-jdtls",
--     ft = { "java" },
--     config = function()
--       local lspconfig = require("lspconfig")
--
--       lspconfig.jdtls.setup({
--         cmd = { "jdtls" },
--         root_dir = lspconfig.util.root_pattern(".git", "pom.xml", "build.gradle"),
--         settings = {
--           java = {
--             signatureHelp = { enabled = true },
--             contentProvider = { preferred = "fernflower" },
--           },
--         },
--         handlers = {
--           ["language/status"] = function(_, _)
--             -- 아무 동작도 하지 않음
--           end,
--           ["$/progress"] = function(_, result, ctx)
--             return -- 진행 상태 업데이트 비활성화
--           end,
--         },
--         init_options = {
--           bundles = {},
--         },
--       })
--     end,
--   },
-- }
